In [38]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import classification_report

In [15]:
df = pd.read_csv('Data_Profil_IG.csv')
df

,id_user,username,fullname,biography,is_private,is_verified,follower_count,following_count,media_count,like_count(last10post),comment_count(last10post),last_post,last_post_interval(days),last_story,last_story_interval(hours),Keaktifan
0,1918078581,raffinagita1717,Raffi Ahmad and Nagita Slavina,(business : ransdigital.id@gmail.com)\nDengeri...,False,True,67300238,5683,18662,1947155,11949,2023-02-24 12:04:01+07:00,0.0,2023-02-24 16:02:10+07:00,0.0,1
1,522969993,ayutingting92,Ayu Tingting,"Check my new product ""@hwasahan.id""\nEndorseme...",False,True,54055703,1382,11774,367625,4336,2023-02-24 09:25:27+07:00,0.0,2023-02-24 15:36:22+07:00,0.0,1
2,225064794,prillylatuconsina96,Prilly Latuconsina,@rebelprincess.id @nonajudesss @bumbunona @sli...,False,True,51287547,2492,6705,1617463,6714,2023-02-23 12:15:46+07:00,1.0,2023-02-24 15:59:57+07:00,0.0,1
3,2993265,laudyacynthiabella,Laudya Cynthia Bella,MasyaALLAH Tabarakallah üíï\nManaged by Admin & ...,False,True,38460524,3009,369,347244,2348,2023-02-15 19:59:13+07:00,8.0,2023-02-24 14:29:50+07:00,1.0,1
4,3261799,gisel_la,Gisella Anastasia,@madame.gie @gofyber @ropangbro.express @tedu....,False,True,37934940,4297,10274,639239,2204,2023-02-24 14:50:57+07:00,0.0,2023-02-24 13:08:26+07:00,3.0,1
5,1948416,lunamaya,Luna Maya,Queen of the Moon üëëüåô \nFounder of @namabeauty....,False,True,36599977,2112,4207,328745,5378,2023-02-23 17:14:57+07:00,0.0,2023-02-24 14:00:06+07:00,2.0,1
6,8115577,raisa6690,NaN,@juni_records / @officialrainebeauty \nI just ...,False,True,35445558,1711,4306,647077,9675,2023-02-23 14:20:30+07:00,1.0,2023-02-24 14:08:23+07:00,2.0,1
7,305384601,viavallen,Via Vallen,I am no longer with Ascada since last year\nFo...,False,True,27951196,354,524,1177553,8391,2023-02-17 17:18:14+07:00,6.0,2023-02-24 03:31:24+07:00,12.0,1
8,5735890,chelseaoliviaa,Chelsea Olivia Wijaya,Indonesian Celebrity ‚Ä¢ \n@glennalinskie üíç ‚Ä¢ üëßüèª...,False,True,28351025,876,3504,235157,1077,2023-02-23 19:44:59+07:00,0.0,2023-02-24 15:04:24+07:00,1.0,1
9,25980770,raditya_dika,Raditya Dika,For business inquiries email to: management@ra...,False,True,21092511,503,5677,869470,5392,2023-02-23 20:35:21+07:00,0.0,2023-02-24 16:06:54+07:00,0.0,1
10,51245593696,denisechariesta91,Denise Chariesta,pembela kebenaran keadilan wa:081991991992 @fl...,False,False,639462,14,838,55098,1457,2023-02-24 15:53:32+07:00,0.0,2023-02-24 16:13:40+07:00,0.0,1
11,624435843,pinkan_mambo,Pinkan Mambo,Wa Show & Endorse /bussiness. Hub Pm office wa...,False,True,303344,414,2433,22114,4047,2022-12-26 08:54:46+07:00,60.0,2023-02-24 00:30:13+07:00,15.0,1
12,288615624,rizkybillar,Muhammad Rizky Billar,@leslar_entertainment \n@leslarmetaverse \n@...,False,True,12653904,876,485,4367550,96195,2023-02-21 16:54:26+07:00,2.0,2023-02-23 17:41:30+07:00,22.0,1
13,1542976680,lestykejora,Lestikejora,@ldaily.id @purnamabeautyofficial \nBA @msglo...,False,True,27059994,2591,978,4430768,49767,2023-02-24 14:04:50+07:00,0.0,2023-02-23 23:04:13+07:00,17.0,1
14,5756510,baimwong,Baim Wong,Jangan Lelah Untuk Berbagi \nSayang Kalian Sem...,False,True,17635487,2532,4187,817688,7452,2023-02-24 14:49:52+07:00,0.0,2023-02-24 10:54:34+07:00,5.0,1
15,50104276,paula_verhoeven,Paula Verhoeven Wong,Public Figure\nMom of\n@kianotigerwong\n@kenzo...,False,True,5976022,2564,1692,684120,3114,2023-02-23 16:28:06+07:00,0.0,2023-02-24 15:07:10+07:00,1.0,1
16,234085386,ybrap,yb,@weird.genius \n@yb_lab\n@ybgocom,False,True,5586799,669,145,1281026,23441,2023-02-22 17:23:58+07:00,1.0,2023-02-24 13:27:07+07:00,2.0,1
17,23400298572,nikitamirzanimawardi_172,Nikita Mirzani üåπ,BA selamanaya @beningsclinic_jakarta @nikitami...,False,True,9750252,67,296,439979,14179,2023-02-24 11:22:09+07:00,0.0,2023-02-24 11:16:27+07:00,5.0,1
18,24239929,princessyahrini,SYAHRINI,NaN,False,True,41845194,756,4628,188237,47,2023-02-23 17:11:44+07:00,0.0,2023-02-24 16:14:08+07:00,0.0,1
19,563409528,syauqikhosyi,Syauqi Khosyi,NaN,False,False,630,813,6,657,51,2022-11-06 17:16:32+07:00,109.0,2023-02-23 23:38:34+07:00,16.0,1
20,1382888167,ester_febiola,Ester Febiola,üåºüçÄ,False,False,1338,1124,0,0,0,NaN,NaN,NaN,NaN,0
21,1368990914,sandrinanajwa,Sandrina Najwa,NaN,False,False,754,570,0,0,0,NaN,NaN,NaN,NaN,0
22,1705712320,bresciaaydna,·¥Ö…™…¥·¥Ä,YOLO,False,False,1026,1899,8,-8,281,2023-01-26 18:18:08+07:00,28.0,NaN,NaN,1
23,3207598639,rizky_ade24,Rizky Ade II,NaN,True,False,226,391,1,0,0,NaN,NaN,NaN,NaN,0
24,4758588217,ameliyah_rskyh,Ameliyah Riskiyah,aeri's\nü¶äüíéüå±\n@baekhyunee_exo,True,False,235,290,0,0,0,NaN,NaN,NaN,NaN,0
25,2248835396,sugab.3gp,bagus adi prayoga,iru <3,False,False,544,921,3,168,22,2023-02-16 11:37:23+07:00,8.0,NaN,NaN,1
26,286877006,jasmineakh,jasmine avrile,NaN,False,False,3141,1911,3,992,43,2022-08-18 15:45:27+07:00,190.0,NaN,NaN,1
27,1994265742,raflyqowi,qowi,hunnn,True,False,949,595,0,0,0,NaN,NaN,NaN,NaN,0
28,3481509055,dwiahmadza,Dwi Ahmad Dzulhijjah,(Lifelong learner)\nPortofolio : @dwiahmad_dz\...,False,False,2319,2172,46,2828,246,2022-07-27 11:35:22+07:00,212.0,NaN,NaN,1
29,1908920707,mriaps,Muhammad Rio Apriansah,UMN '20'\nBasic.,False,False,1174,762,3,186,9,2020-07-06 20:06:29+07:00,962.0,NaN,NaN,1
30,1686914046,musfirotul_,ra.,NaN,True,False,1035,702,1,0,0,NaN,NaN,NaN,NaN,0
31,52358146457,mjji.bri.ll,Bri,NaN,False,False,66,62,16,187,28,2023-02-23 09:09:21+07:00,1.0,NaN,NaN,1
32,58001969444,yudisghifari,yudis ghifari,Akun lama suspend,False,False,73,120,1,26,0,2023-02-14 11:19:06+07:00,10.0,NaN,NaN,1
33,598772637,azalia_tambunan,Azalia M.S. Tambunan,Just a girl having fun in the big big world,False,False,793,792,7,1204,48,2023-02-21 17:13:54+07:00,2.0,NaN,NaN,1
34,1255561290,nzhf.idzthr,Nazhiifah Nawaal,Al-'Araf:199‚ú®,False,False,915,1011,3,134,1,2023-02-06 20:20:38+07:00,17.0,NaN,NaN,1
35,2248538523,hasnabila00,Nabilah Hasna,Faculty of Psychology \nPadjadjaran University,False,False,211,285,3,123,8,2021-07-06 21:07:48+07:00,597.0,NaN,NaN,1
36,8522446171,llfdlh2,llfdlh,NaN,False,False,384,376,18,334,13,2023-01-03 01:13:52+07:00,52.0,NaN,NaN,1
37,1519756238,andirayunitha,Andira Yunita,NaN,False,False,2927,2015,15,2352,169,2023-01-17 20:00:30+07:00,37.0,NaN,NaN,1
38,1942891275,adnmhrn_,Dinda Maharani,NaN,False,False,557,337,0,0,0,NaN,NaN,NaN,NaN,0
39,4755465472,uenomeaneo,NaN,NaN,True,False,503,432,2,0,0,NaN,NaN,NaN,NaN,0
40,1536392493,salsakhayyira,salsiii,„ÇÇ„ÅÜÊ£Æ„Å∏Â∏∞„Çç„ÅÜ„Åã ?\nË°ó„Å´„ÅØ‰Ωï„ÇÇ„Å™„Åã„Å£„Åü. \nDKV TelU 20‚Äô,False,False,529,444,17,1300,93,2021-11-05 07:55:02+07:00,476.0,NaN,NaN,1
41,1276944323,athaliapuspa,Athalia,NaN,True,False,811,643,0,0,0,NaN,NaN,NaN,NaN,0
42,37701555870,intanmdnu,üåä,reborn,True,False,167,216,0,0,0,NaN,NaN,NaN,NaN,0
43,2109551495,bintangagastiya_,Bintang Agastiya,what should I put here?,False,False,2540,816,0,0,0,NaN,NaN,NaN,NaN,0
44,1712942455,rizkyagustisap,Aulia Rizky Agusti Saputri,NaN,False,False,1694,1189,16,2314,84,2023-01-23 19:07:30+07:00,31.0,NaN,NaN,1
45,2879889275,amandaptrya,ùìêùì∂ùì™ùì∑ùì≠ùì™ ùìüùìæùìΩùìªùì≤ùîÇùì™ùì∑ùìΩùì≤,Thinking of you.,True,False,907,890,1,0,0,NaN,NaN,NaN,NaN,0
46,3064853276,ahsnul.q,ahsanul haq,Part of @forpeople.id\n‚úç Collabs with me just DM,True,False,733,516,10,0,0,NaN,NaN,NaN,NaN,0
47,1489315478,divathayeb,Diva Salsabila,@_divaat,True,False,1626,1303,32,0,0,NaN,NaN,NaN,NaN,0
48,9931640017,vatwatlmr,ùëΩùíÇùíïùíòùíÇùíïùíñùíç ùë¥ùíñùíïùíäùíÇ ùëπùíÇùíâùíéùíÇùíï,üìçKarawang-Purbalingga,False,False,598,548,0,0,0,NaN,NaN,NaN,NaN,0
49,18789452458,ashyep_,NaN,Akun first ke hacküôÅ,True,False,169,183,3,0,0,NaN,NaN,NaN,NaN,0
50,1570222727,retnowynti,Retno Wijayanti,NaN,True,False,936,621,0,0,0,NaN,NaN,NaN,NaN,0
51,3654850700,fathonizkr,NaN,u dunno me,False,False,876,780,9,-9,55,2022-11-21 22:18:29+07:00,94.0,NaN,NaN,1
52,2271037529,smrmendem,Dimas Adi,A long way up to the summit.,False,False,118,80,4,32,8,2023-01-13 19:13:28+07:00,41.0,NaN,NaN,1
53,5371286272,hafifarhans,De_Farhana,ü•àI want to be useful with all of them aamiinü•∫\...,False,False,407,639,33,859,91,2022-01-19 12:18:28+07:00,401.0,NaN,NaN,1
54,7737040222,nandi_ir,Nandi Irawan,NaN,True,False,228,362,3,0,0,NaN,NaN,NaN,NaN,0
55,3101437999,mochilhamsyah_,heuh hayoh,NaN,True,False,566,625,3,0,0,NaN,NaN,NaN,NaN,0

In [16]:
data = df[['id_user','username', 'follower_count', 'media_count', 'like_count(last10post)', 'comment_count(last10post)', 'last_post_interval(days)', 'last_story_interval(hours)', 'Keaktifan']]
data

,id_user,username,follower_count,media_count,like_count(last10post),comment_count(last10post),last_post_interval(days),last_story_interval(hours),Keaktifan
0,1918078581,raffinagita1717,67300238,18662,1947155,11949,0.0,0.0,1
1,522969993,ayutingting92,54055703,11774,367625,4336,0.0,0.0,1
2,225064794,prillylatuconsina96,51287547,6705,1617463,6714,1.0,0.0,1
3,2993265,laudyacynthiabella,38460524,369,347244,2348,8.0,1.0,1
4,3261799,gisel_la,37934940,10274,639239,2204,0.0,3.0,1
5,1948416,lunamaya,36599977,4207,328745,5378,0.0,2.0,1
6,8115577,raisa6690,35445558,4306,647077,9675,1.0,2.0,1
7,305384601,viavallen,27951196,524,1177553,8391,6.0,12.0,1
8,5735890,chelseaoliviaa,28351025,3504,235157,1077,0.0,1.0,1
9,25980770,raditya_dika,21092511,5677,869470,5392,0.0,0.0,1
10,51245593696,denisechariesta91,639462,838,55098,1457,0.0,0.0,1
11,624435843,pinkan_mambo,303344,2433,22114,4047,60.0,15.0,1
12,288615624,rizkybillar,12653904,485,4367550,96195,2.0,22.0,1
13,1542976680,lestykejora,27059994,978,4430768,49767,0.0,17.0,1
14,5756510,baimwong,17635487,4187,817688,7452,0.0,5.0,1
15,50104276,paula_verhoeven,5976022,1692,684120,3114,0.0,1.0,1
16,234085386,ybrap,5586799,145,1281026,23441,1.0,2.0,1
17,23400298572,nikitamirzanimawardi_172,9750252,296,439979,14179,0.0,5.0,1
18,24239929,princessyahrini,41845194,4628,188237,47,0.0,0.0,1
19,563409528,syauqikhosyi,630,6,657,51,109.0,16.0,1
20,1382888167,ester_febiola,1338,0,0,0,NaN,NaN,0
21,1368990914,sandrinanajwa,754,0,0,0,NaN,NaN,0
22,1705712320,bresciaaydna,1026,8,-8,281,28.0,NaN,1
23,3207598639,rizky_ade24,226,1,0,0,NaN,NaN,0
24,4758588217,ameliyah_rskyh,235,0,0,0,NaN,NaN,0
25,2248835396,sugab.3gp,544,3,168,22,8.0,NaN,1
26,286877006,jasmineakh,3141,3,992,43,190.0,NaN,1
27,1994265742,raflyqowi,949,0,0,0,NaN,NaN,0
28,3481509055,dwiahmadza,2319,46,2828,246,212.0,NaN,1
29,1908920707,mriaps,1174,3,186,9,962.0,NaN,1
30,1686914046,musfirotul_,1035,1,0,0,NaN,NaN,0
31,52358146457,mjji.bri.ll,66,16,187,28,1.0,NaN,1
32,58001969444,yudisghifari,73,1,26,0,10.0,NaN,1
33,598772637,azalia_tambunan,793,7,1204,48,2.0,NaN,1
34,1255561290,nzhf.idzthr,915,3,134,1,17.0,NaN,1
35,2248538523,hasnabila00,211,3,123,8,597.0,NaN,1
36,8522446171,llfdlh2,384,18,334,13,52.0,NaN,1
37,1519756238,andirayunitha,2927,15,2352,169,37.0,NaN,1
38,1942891275,adnmhrn_,557,0,0,0,NaN,NaN,0
39,4755465472,uenomeaneo,503,2,0,0,NaN,NaN,0
40,1536392493,salsakhayyira,529,17,1300,93,476.0,NaN,1
41,1276944323,athaliapuspa,811,0,0,0,NaN,NaN,0
42,37701555870,intanmdnu,167,0,0,0,NaN,NaN,0
43,2109551495,bintangagastiya_,2540,0,0,0,NaN,NaN,0
44,1712942455,rizkyagustisap,1694,16,2314,84,31.0,NaN,1
45,2879889275,amandaptrya,907,1,0,0,NaN,NaN,0
46,3064853276,ahsnul.q,733,10,0,0,NaN,NaN,0
47,1489315478,divathayeb,1626,32,0,0,NaN,NaN,0
48,9931640017,vatwatlmr,598,0,0,0,NaN,NaN,0
49,18789452458,ashyep_,169,3,0,0,NaN,NaN,0
50,1570222727,retnowynti,936,0,0,0,NaN,NaN,0
51,3654850700,fathonizkr,876,9,-9,55,94.0,NaN,1
52,2271037529,smrmendem,118,4,32,8,41.0,NaN,1
53,5371286272,hafifarhans,407,33,859,91,401.0,NaN,1
54,7737040222,nandi_ir,228,3,0,0,NaN,NaN,0
55,3101437999,mochilhamsyah_,566,3,0,0,NaN,NaN,0

In [18]:
data.isnull().sum()

id_user                        0
username                       0
follower_count                 0
media_count                    0
like_count(last10post)         0
comment_count(last10post)      0
last_post_interval(days)      19
last_story_interval(hours)    36
Keaktifan                      0
dtype: int64

In [20]:
data['last_post_interval(days)'] = data['last_post_interval(days)'].replace(np.nan, 0)
data['last_story_interval(hours)'] = data['last_story_interval(hours)'].replace(np.nan, 0)

C:\Users\RanggaSaputra\AppData\Local\Temp\ipykernel_5352\1706521632.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['last_post_interval(days)'] = data['last_post_interval(days)'].replace(np.nan, 0)
C:\Users\RanggaSaputra\AppData\Local\Temp\ipykernel_5352\1706521632.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['last_story_interval(hours)'] = data['last_story_interval(hours)'].replace(np.nan, 0)

In [22]:
data.isnull().sum()

id_user                       0
username                      0
follower_count                0
media_count                   0
like_count(last10post)        0
comment_count(last10post)     0
last_post_interval(days)      0
last_story_interval(hours)    0
Keaktifan                     0
dtype: int64

In [32]:
data['Keaktifan'].value_counts()

1    37
0    19
Name: Keaktifan, dtype: int64

In [28]:
X = data[['follower_count', 'media_count', 'like_count(last10post)', 'comment_count(last10post)', 'last_post_interval(days)', 'last_story_interval(hours)']]
y = data['Keaktifan']

In [29]:
from imblearn.over_sampling import SMOTE
X_resampled, y_resampled = SMOTE(random_state=4).fit_resample(X, y)

In [30]:
y_resampled.value_counts()

1    37
0    19
Name: Keaktifan, dtype: int64

In [41]:
# Split data into training and testing set
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# Create logistic regression model
model = LogisticRegression()

# Train model on training set
model.fit(X_train, y_train)

# Make predictions on testing set
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = model.score(X_test, y_test)
print('Accuracy:', accuracy)

Accuracy: 0.9333333333333333

C:\Users\RanggaSaputra\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [42]:
print(classification_report(y_test, y_pred, zero_division=0))
print(f'confusion matrix:\n {confusion_matrix(y_test,  y_pred)}')

              precision    recall  f1-score   support

           0       0.83      1.00      0.91         5
           1       1.00      0.90      0.95        10

    accuracy                           0.93        15
   macro avg       0.92      0.95      0.93        15
weighted avg       0.94      0.93      0.93        15

confusion matrix:
 [[5 0]
 [1 9]]

In [43]:
from sklearn.ensemble import RandomForestClassifier

# Create random forest model
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train model on training set
model.fit(X_train, y_train)

# Make predictions on testing set
y_pred = model.predict(X_test)

# Calculate accuracy
accuracy = model.score(X_test, y_test)
print('Accuracy:', accuracy)

Accuracy: 1.0

In [44]:
print(classification_report(y_test, y_pred, zero_division=0))
print(f'confusion matrix:\n {confusion_matrix(y_test,  y_pred)}')

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00        10

    accuracy                           1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15

confusion matrix:
 [[ 5  0]
 [ 0 10]]