In [1]:
from facebook_scraper import *
#from facebook_scraper import get_profile
#from facebook_scraper import get_group_info

import datetime
import pandas as pd
import re

C:\Users\RanggaSaputra\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
name_user_account = input("Link Id : ")

Link Id : ani.wahyudi.754

In [5]:
type(name_user_account)

str

In [ ]:
#names = ['andika.koja.3', 'ani.wahyudi.754', 'rhosi.ajjh','fani.chindra', 'bayu.tricandraputra', 'andika.restu.798', 'adi.priyatama.71', 'reva.marsya.5', 'deawhiie', 'matthew.nahor.9', 'pathola.riez', 'meita.hofifah.7', 'nada.indrianisiregar', 'dedev.alyssa']

g = get_group_info("makeupartistsgroup", cookies = {'sb': 'jYr1Y026A-2VjDm_XJBR6ETZ', 'datr': 'j4r1Y1Hi2f_ST4wVzobNFmCL', 'dpr': '1.5', 'c_user': '100001581864778', 'xs': '30%3AopPGizY1F1mghA%3A2%3A1677036201%3A-1%3A11175', 'fr': '0NJTocD2fx3WXJcHm.AWVFijqYbwIsqU_014egTaWO3ag.Bj9YqN.FZ.AAA.0.0.Bj9Yqt.AWVTp-49XAI', 'wd': '1280x569'})

## Get Data Profile From Users

In [8]:
data_FB_profile = []

profile = get_profile(name_user_account, cookies = {'sb': 'jYr1Y026A-2VjDm_XJBR6ETZ', 'datr': 'j4r1Y1Hi2f_ST4wVzobNFmCL', 'dpr': '1.5', 'c_user': '100001581864778', 'xs': '30%3AopPGizY1F1mghA%3A2%3A1677036201%3A-1%3A11175', 'fr': '0NJTocD2fx3WXJcHm.AWVFijqYbwIsqU_014egTaWO3ag.Bj9YqN.FZ.AAA.0.0.Bj9Yqt.AWVTp-49XAI', 'wd': '1280x569'})
    
#get employment data from user
try :
    start_year = '-'
    last_year = '-'
    company = '-'
    
    employment_data = profile['Pekerjaan'].split('\n')
    data_profile = employment_data[0:3]
    term = []

    for i in range(len(data_profile)):
        company = data_profile[0]
        term.append(re.findall(r'\d+', data_profile[i]))
    for j in range(len(term)):
        for k in range(len(term[j])):
            if term[j] == None:
                break
            else:
                if str(term[j][k]).isdigit() == True:
                    start_year = data_profile[j].split(' - ')[0]
                    last_year = data_profile[j].split(' - ')[-1]
                    if last_year == 'Sekarang':
                        last_year = 'Now'
                        #tahun_akhir = datetime.date.today()
                        #tahun_akhir = tahun_akhir.strftime("%d %B %Y")

except:
    start_year = '-'
    last_year = '-'
    company = '-'
        
# get general information from user
try:
    birth_day = '-'
    sex = '-'
    language = '-'
    
    general_info = profile['Info Umum'].split('\n')

    for i in range(1, len(general_info), 2):
        if general_info[i] == 'Tanggal Lahir':
            birth_day = general_info[i-1]
        elif general_info[i] == 'Jenis Kelamin':
            sex = general_info[i-1]
        else:
            language = general_info[i-1]

except:
    birth_day = '-'
    sex = '-'
    language = '-'
        
#get residence data from the user
try:
    hometown = '-'
    current_city = '-'
    
    place = profile['Pernah Tinggal di'].split('\n')
        
    for i in range(1, len(place), 2):
        if place[i] == 'Kota asal':
            hometown = place[i-1]
        elif place[i] == 'Kota Saat Ini':
            current_city = place[i-1]
except:
    hometown = '-'
    current_city = '-'
        
#get last education level data from user
try:
    last_education = profile['Pendidikan'].split('\n')
    school = last_education[0]
    level_education = last_education[1]
        
except:
    school = '-'
    level_education = '-'
        
#get family members data from user
try:
    family = profile['Anggota Keluarga'].split('\n')
    family_member_name = family[0]
    family_relationship = family[1]
    
except:
    family_member_name = '-'
    family_relationship = '-'
            
data_FB_profile.append({
        'Id_user': profile['id'],
        'Nama' : profile['Name'],
        'Tanggal_lahir' : birth_day,
        'Sex' : sex,
        'Asal' : hometown,
        'Domisili' : current_city,
        'Asal_Sekolah_Terakhir': school,
        'Pendidikan_Terakhir': level_education,
        'Tempat_Kerja(last)' : company,
        'Tahun_mulai' : start_year,
        'Tahun_akhir_bekerja' : last_year,
        'Nama_Anggota_Keluarga' : family_member_name,
        'Hubungan_Keluarga' : family_relationship})

In [9]:
data_profile = pd.DataFrame(data_FB_profile)
data_profile

,Id_user,Nama,Tanggal_lahir,Sex,Asal,Domisili,Asal_Sekolah_Terakhir,Pendidikan_Terakhir,Tempat_Kerja(last),Tahun_mulai,Tahun_akhir_bekerja,Nama_Anggota_Keluarga,Hubungan_Keluarga
0,100004996871880,Ani Wahyudi,-,Perempuan,"Jakarta, Indonesia",Depok,Smk Putra Bangsa Depok,SMA,Tenaga Pendidik PAUD,-,-,Sri badriati khusna,Anak

## Data Postingan FB

In [12]:
data_FB_post = []

postan = []
    
user = get_posts(name_user_account, pages=1, options={'reactors': True}, cookies= {'sb': 'jYr1Y026A-2VjDm_XJBR6ETZ', 'datr': 'j4r1Y1Hi2f_ST4wVzobNFmCL', 'dpr': '1.5', 'c_user': '100001581864778', 'xs': '30%3AopPGizY1F1mghA%3A2%3A1677036201%3A-1%3A11175', 'fr': '0NJTocD2fx3WXJcHm.AWVFijqYbwIsqU_014egTaWO3ag.Bj9YqN.FZ.AAA.0.0.Bj9Yqt.AWVTp-49XAI', 'wd': '1280x569'})
    
for post in user:
    postan.append(post)
        
    
for posting in postan:
        
    #get post_id
    id_post = posting['post_id']
        
    #get text from post
    try:
        text_postingan = posting['text']
            
        if text_postingan == '':
            text_postingan = 'Tidak ada data'
    except:
        text_postingan = '-'
        
    #get date posting
    time = posting['time'].strftime("%d %B %Y")
        
    #get reactions
    try:
        like = posting['reactions']['suka']
    except:
        like = 0
            
    try:
        care = posting['reactions']['care']
    except:
        care = 0
        
    try:
        laugh = posting['reactions']['haha']
    except:
        laugh = 0
            
    try:
        angry = posting['reactions']['angry']
    except:
        angry = 0
            
    try:
        sad = posting['reactions']['sad']
    except:
        sad = 0
            
    try:
        love = posting['reactions']['love']
    except:
        love = 0
            
    try:
        wow = posting['reactions']['wow']
    except:
        wow = 0
            
    data_FB_post.append({
            'Id_user': post['user_id'],
            'Nama' : post['username'],
            'post_id' : id_post,
            'waktu_upload': time,
            'teks_postingan' : text_postingan,
            'reaksi_like' : like,
            'reaksi_care' : care,
            'reaksi_laugh' : laugh,
            'reaksi_angry' : angry,
            'reaksi_sad' : sad,
            'reaksi_love' : love,
            'reaksi_wow' : wow})

C:\Users\RanggaSaputra\AppData\Local\Programs\Python\Python310\lib\site-packages\IPython\core\interactiveshell.py:3378: UserWarning: A low page limit (<=2) might return no results, try increasing the limit
  exec(code_obj, self.user_global_ns, self.user_ns)
C:\Users\RanggaSaputra\AppData\Local\Programs\Python\Python310\lib\site-packages\dateparser\freshness_date_parser.py:76: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  now = self.get_local_tz().localize(now)

In [13]:
data_postingan = pd.DataFrame(data_FB_post)
data_postingan.tail()

,Id_user,Nama,post_id,waktu_upload,teks_postingan,reaksi_like,reaksi_care,reaksi_laugh,reaksi_angry,reaksi_sad,reaksi_love,reaksi_wow
5,100004996871880,Ani Wahyudi,2511531169023421,14 February 2023,Apa si hebatnya natura??\n\n1. Engga bikin ket...,0,0,0,0,0,0,0
6,100004996871880,Ani Wahyudi,2497644380412100,28 January 2023,Kenapa zombie kalau nyerang musti bareng-baren...,0,0,0,0,0,0,0
7,100004996871880,Ani Wahyudi,2497359863773885,28 January 2023,Alhamdulillah Duet Host yang super duper rame ...,0,0,0,0,0,0,0
8,100004996871880,Ani Wahyudi,2491596577683547,21 January 2023,Alhamdulillah akhirnya bisa tidur dengan nyeny...,0,0,0,0,0,0,0
9,100004996871880,Ani Wahyudi,2486154921561046,14 January 2023,Iseng2 melukis di media topi caping..... Walau...,0,0,0,0,0,0,0